# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - image-search-autopart

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52E7E5DD6E3F4A35B3C736D90ADC4ED8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D4A067D8E7B94D5DB75B3A563D5598B8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA40BE994E8E4634BB8A15533715B59E }}

      - name: 'Pre-deployment checks and wait'
        run: |
          echo "Checking production deployment readiness..."
          # Check if the production app is currently deploying or locked
          curl -s -f --connect-timeout 30 https://image-search-autopart.azurewebsites.net/health || echo "Production app may be updating..."
          echo "Waiting to avoid deployment conflicts and ensure clean deployment state..."
          sleep 90

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'image-search-autopart'
          slot-name: 'Production'
        continue-on-error: false
        timeout-minutes: 15
      
      - name: 'Post-deployment wait and validation'
        run: |
          echo "Production deployment completed. Waiting for container stabilization..."
          sleep 120
          echo "Starting comprehensive production application validation..."
          
          # Health check with extended retry
          for i in {1..15}; do
            echo "Production health check attempt $i/15..."
            if curl -s -f --connect-timeout 30 --max-time 60 https://image-search-autopart.azurewebsites.net/health; then
              echo "✓ Production health check successful!"
              break
            fi
            if [ $i -eq 15 ]; then
              echo "❌ Production health check failed after 15 attempts"
              exit 1
            fi
            sleep 20
          done
          
          # Warmup home endpoint
          echo "Warming up production application..."
          for i in {1..10}; do
            echo "Production warmup attempt $i/10..."
            if curl -s -f --connect-timeout 30 --max-time 60 https://image-search-autopart.azurewebsites.net/home; then
              echo "✓ Production application warmup successful!"
              break
            fi
            sleep 15
          done
          
          echo "🎉 Production deployment validation completed successfully!"
          